[build]
  command = "npm run -w @oklab/app build"
  publish = "packages/app/dist"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.environment]
  NODE_VERSION = "20"
